services:
  - type: web
    name: metabase
    env: docker
    plan: starter
    dockerfile: Dockerfile
    buildCommand: |
      echo "Building Metabase container..."
    startCommand: |
      docker run -d -p 3000:3000 \
        -e "MB_DB_TYPE=postgres" \
        -e "MB_DB_DBNAME=postgres" \
        -e "MB_DB_PORT=6543" \
        -e "MB_DB_USER=postgres.whyavrfcbyjmchtsfwin" \
        -e "MB_DB_PASS=IDa3uCSQF9VSw1Ul" \
        -e "MB_DB_HOST=aws-0-sa-east-1.pooler.supabase.com" \
        --name metabase metabase/metabase
    environment:
      - key: MB_DB_TYPE
        value: postgres
      - key: MB_DB_DBNAME
        value: postgres
      - key: MB_DB_PORT
        value: "6543"
      - key: MB_DB_USER
        value: postgres.whyavrfcbyjmchtsfwin
      - key: MB_DB_PASS
        value: IDa3uCSQF9VSw1Ul
      - key: MB_DB_HOST
        value: aws-0-sa-east-1.pooler.supabase.com
    port: 3000
