services:
  - type: web
    name: metabase
    env: docker
    plan: free
    dockerfile_path: ./Dockerfile
    port: 80  # Porta externa exposta na web
    build_command: ""
    start_command: "java -DMB_JETTY_PORT=3000 -jar metabase.jar"
